// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LxY5ZHHRRwxKwrIHG-7beAA3gwLJ2Og',
    appId: '1:831742840478:web:503bd910acad2836d7758f',
    messagingSenderId: '831742840478',
    projectId: 'applestudentcommunity-374f9',
    authDomain: 'applestudentcommunity-374f9.firebaseapp.com',
    storageBucket: 'applestudentcommunity-374f9.appspot.com',
    measurementId: 'G-MQZN7X4JRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAa8FQ4oqiTYJLdYzDJmTK5qTnJqK75c',
    appId: '1:831742840478:android:d074f2a37748d0a2d7758f',
    messagingSenderId: '831742840478',
    projectId: 'applestudentcommunity-374f9',
    storageBucket: 'applestudentcommunity-374f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91bXLyCmApKC-VQWiYOZvuhUxLLIZKck',
    appId: '1:831742840478:ios:9e2d161c3cba9f3bd7758f',
    messagingSenderId: '831742840478',
    projectId: 'applestudentcommunity-374f9',
    storageBucket: 'applestudentcommunity-374f9.appspot.com',
    iosClientId: '831742840478-6s5o71dp3ua3q17o306nl0vpcu7bnqa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleStudentCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91bXLyCmApKC-VQWiYOZvuhUxLLIZKck',
    appId: '1:831742840478:ios:9e2d161c3cba9f3bd7758f',
    messagingSenderId: '831742840478',
    projectId: 'applestudentcommunity-374f9',
    storageBucket: 'applestudentcommunity-374f9.appspot.com',
    iosClientId: '831742840478-6s5o71dp3ua3q17o306nl0vpcu7bnqa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleStudentCommunity',
  );
}
